Link TFConnect news to threefold_io RSS
threefoldtech/threefold_connect pull request #625
Opened 2024-10-09 14:35 UTC by AlaaElattar

- https://github.com/threefoldtech/threefold_connect_news/issues/5

2024-10-10 11:51 UTC, AhmedHanafy725 requested changes
it might have double spinners if the user scrolled twice, let's block the second one

<img src="https://github.com/user-attachments/assets/70dce264-ffd5-44b1-b096-ff92e6e14cdf" width="250">

2024-10-10 11:51 UTC, AhmedHanafy725 commented on app/lib/apps/news/news_screen.dart
> +                      padding: const EdgeInsets.all(8.0),
```suggestion
                      padding: const EdgeInsets.all(16),
```

2024-10-10 11:51 UTC, AhmedHanafy725 commented on app/lib/apps/news/news_screen.dart
> +                                width: 20,
this icon needs to have color based on the theme mode.

2024-10-11 12:14 UTC, AlaaElattar commented
https://github.com/user-attachments/assets/b211ae15-d6d9-428b-9615-90c4acce0889

2024-10-13 05:28 UTC, AhmedHanafy725 commented on app/lib/apps/news/news_screen.dart
> +                        'Loading Articles ...',
```suggestion
                        'Loading Articles...',
```

2024-10-13 19:21 UTC, AhmedHanafy725 approved these changes

2024-10-13 19:22 UTC, merged