Update regex of email validation
threefoldtech/threefold_connect pull request #682
Opened 2024-10-30 12:07 UTC by AlaaElattar

- https://github.com/threefoldtech/threefold_connect/issues/541
- Update verification to ensure that there’s a dot followed by at least two letters at the end, which prevents invalid entries like `aa@aa`.

2024-11-04 15:46 UTC, zaelgohary requested changes
The regex accepts the following invalid scenarios:

- Two or more consecutive dots in the local part

![image](https://github.com/user-attachments/assets/2d53a0aa-ae0b-4e2d-93b4-472434d32f31)

- Invalid max length

![image](https://github.com/user-attachments/assets/9f1bc0d4-34ac-4fd6-834f-69a1ebd1a80d)

- Hyphens at invalid positions in the domain

![image](https://github.com/user-attachments/assets/0428faea-c00a-434a-935b-742af59ec4ea)

![image](https://github.com/user-attachments/assets/7686e106-aa6f-4e1c-8b1a-8fd5f52db247)

- Leading or trailing dot in the local part

![image](https://github.com/user-attachments/assets/1ecc9864-dbb3-45d5-8717-7a3669abbe1c)

![image](https://github.com/user-attachments/assets/5d0c3283-9359-4ee0-b8d9-722f1002baa3)

2024-11-05 10:38 UTC, AlaaElattar commented
![image](https://github.com/user-attachments/assets/fd49ebc8-9969-4dd8-aec0-a428a243f697)
![image](https://github.com/user-attachments/assets/2d65f09b-2b2e-4b9c-bb17-4a6323dc4b2e)
![image](https://github.com/user-attachments/assets/f6b9be92-8d80-434d-af5e-b048b3521800)
![image](https://github.com/user-attachments/assets/95438679-3891-45e0-999c-89c6395648bd)
![image](https://github.com/user-attachments/assets/d453b595-3682-46dd-a1f3-80beb9ea6d18)

2024-11-05 10:52 UTC, zaelgohary reviewed
Can we use email validator instead of regex?

2024-11-06 11:24 UTC, zaelgohary commented on app/lib/services/tools_service.dart
> +  return EmailValidator.validate(value);
Can we use isEmail from validators instead?

2024-11-06 11:37 UTC, zaelgohary approved these changes

2024-11-19 06:24 UTC, AhmedHanafy725 approved these changes

2024-11-21 09:55 UTC, merged