check on mnemonic when confirming seed
threefoldtech/threefold_connect pull request #696
Opened 2024-10-31 05:43 UTC by AlaaElattar

- https://github.com/threefoldtech/threefold_connect/issues/549
- Converting list of entered words to set and check if their length still 3 or not.

2024-11-04 15:03 UTC, zaelgohary commented
Please add tested scenarios.

2024-11-04 15:14 UTC, zaelgohary approved these changes

2024-11-05 09:11 UTC, AlaaElattar commented
> Please add tested scenarios.

done

2024-11-19 07:40 UTC, AhmedHanafy725 requested changes

2024-11-19 07:40 UTC, AhmedHanafy725 commented on app/lib/screens/mobile_registration_screen.dart
> +    if(enteredWords.length != 3 || enteredWords.toSet().length != 3){
more than 3 words should be allowed too
```suggestion
    if(enteredWords.length < 3 || enteredWords.toSet().length < 3){
```

2024-11-19 07:40 UTC, AhmedHanafy725 commented on app/lib/screens/mobile_registration_screen.dart
> +    }
let's move this logic inside the `validateSeedWords` method

2024-11-21 09:21 UTC, AhmedHanafy725 commented on app/lib/services/tools_service.dart
>    if (words.length != 3) return false;
```suggestion
  if (words.length < 3) return false;
```

2024-11-24 12:34 UTC, AhmedHanafy725 approved these changes

2024-11-24 12:45 UTC, merged