Add chain type to contact err msg
threefoldtech/threefold_connect pull request #713
Opened 2024-11-04 10:14 UTC by zaelgohary

Related issue:

https://github.com/threefoldtech/threefold_connect/issues/605

2024-11-07 07:12 UTC, AlaaElattar approved these changes

2024-11-21 10:27 UTC, AhmedHanafy725 requested changes

2024-11-21 10:27 UTC, AhmedHanafy725 commented on app/lib/widgets/wallets/add_edit_contact.dart
> +      addressError = 'Address exists in ${contacts.first.type.name}';
```suggestion
      addressError = 'Address exists in another ${contacts.first.type.name} contact';

```

2024-11-21 13:00 UTC, AhmedHanafy725 approved these changes

2024-11-21 13:04 UTC, merged