Add Bridge screen
threefoldtech/threefold_connect pull request #762
Opened 2024-11-20 17:46 UTC by zaelgohary

- Add bridge screen
- Fix ContactsScreen typo

2024-11-21 11:10 UTC, zaelgohary commented
@AhmedHanafy725 I set the minimum amount for swapping to be 2 just as in the Dashboard. Same for the Deposit.

2024-11-28 14:00 UTC, AhmedHanafy725 requested changes

2024-11-28 14:00 UTC, AhmedHanafy725 commented on app/assets/tf_chain.png
I think `tft_icon.png` is the same as this one.

2024-11-28 14:00 UTC, AhmedHanafy725 commented on app/lib/models/wallet.dart
> +enum TransactionType { Withdraw, Deposit }
can we use a better name? `BridgeOperation` maybe

2024-11-28 14:00 UTC, AhmedHanafy725 commented on app/lib/widgets/wallets/balance_tile.dart
> +        name == ChainType.Stellar ? 'Stellar' : 'TFChain',
```suggestion
        name.name,
```

2024-11-28 14:00 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/bridge.dart
> +    final bool hideDeposit = widget.wallet.stellarBalance == '-1';
please use a better name as we don't hide it, we disable it

2024-11-28 14:00 UTC, AhmedHanafy725 commented on app/lib/widgets/wallets/swap_transaction_widget.dart
> +            : 'TFChain';
it would be easier if we used one condition
```dart
    final String leftIcon;
    final String leftChainLabel;
    final String rightIcon;
    final String rightChainLabel;
    if (currentTransactionType == TransactionType.Withdraw) {
      leftIcon = widget.withdrawIcon;
      leftChainLabel = 'TFChain';
      rightIcon = widget.depositIcon;
      rightChainLabel = 'Stellar';
    } else {
      leftIcon = widget.depositIcon;
      leftChainLabel = 'Stellar';
      rightIcon = widget.withdrawIcon;
      rightChainLabel = 'TFChain';
    }

```

2024-11-28 14:00 UTC, AhmedHanafy725 commented on app/lib/widgets/wallets/swap_transaction_widget.dart
> +        color: colorScheme.primary.withOpacity(0.1),
```suggestion
        color: colorScheme.surfaceContainerHigh,

```

2024-11-28 14:00 UTC, AhmedHanafy725 commented on app/lib/widgets/wallets/swap_transaction_widget.dart
> +                ),
```suggestion
                Image.asset(
                    leftIcon,
                    fit: BoxFit.contain,
                    color: colorScheme.onSurface,
                    width: 30,
                    height: 30,
                  ),
                

```

2024-11-28 14:00 UTC, AhmedHanafy725 commented on app/lib/widgets/wallets/swap_transaction_widget.dart
> +                        ? colorScheme.onSurface
```suggestion
                        ? colorScheme.onSurface.withOpacity(0.5)

```

2024-11-28 14:00 UTC, AhmedHanafy725 commented on app/lib/widgets/wallets/bridge_confirmation.dart
> +                : 'Deposit Confirmation',
we can't say withdraw or deposit as we use both chains on the app. We are bridging from one to the other

2024-11-28 14:00 UTC, AhmedHanafy725 commented on app/lib/widgets/wallets/bridge_confirmation.dart
> +        await Stellar.transfer(widget.secret, Globals().bridgeTFTAddress,
this should be set on the `flags.dart` file to get its value. I have set it to `bridge-address` on flagsmith

2024-12-04 08:17 UTC, AhmedHanafy725 requested changes

2024-12-04 08:17 UTC, AhmedHanafy725 commented on app/lib/services/tfchain_service.dart
> +Future<String> getMemo(String secret, String address) async {
There is no need to send a secret to this method, we can use QueryClient directly

2024-12-04 08:17 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/bridge.dart
> +        widget.wallet.tfchainSecret, toController.text.trim());
what if the `toAddress` is a stellar address?

2024-12-04 08:17 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/bridge.dart
> +                                  wallets: widget.allWallets,
In the case of Stellar, please make sure that we only add the activated wallets.

2024-12-04 08:17 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/bridge.dart
> +    if (transactionType == BridgeOperation.Deposit) {
in the case of tfchain address, we need to add validation to check if it has a twin

2024-12-04 08:17 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/bridge.dart
> +      if (!isValidStellarAddress(toAddress)) {
also check if the account is activated and has the TFT trustline

2024-12-04 08:17 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/bridge.dart
> +                      labelText: 'Amount (Balance: $balance)',
please apply the new formating on this balance

2024-12-04 08:17 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/bridge.dart
> +    if (disableDeposit) {
please check if the current operation is different to change it, as it will reset the address after picking a new address from the contacts.

2024-12-04 08:17 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/bridge.dart
> +class _WalletBridgeScreenSate extends State<WalletBridgeScreen> {
```suggestion
  State<WalletBridgeScreen> createState() => _WalletBridgeScreenState();
}

class _WalletBridgeScreenState extends State<WalletBridgeScreen> {
```

2024-12-09 13:11 UTC, AhmedHanafy725 requested changes
the deposit is broken

2024-12-09 13:11 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/bridge.dart
> +                  !isWithdraw ? _loadStellarBalance : _loadTFChainBalance,
```suggestion
              secret: !isWithdraw
                  ? widget.wallet.tfchainSecret
                  : widget.wallet.stellarSecret,
              from: fromController.text.trim(),
              to: toController.text.trim(),
              amount: amountController.text.trim(),
              memo: memoText,
              reloadBalance:
                  isWithdraw ? _loadTFChainBalance : _loadStellarBalance,
```

2024-12-09 13:11 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/bridge.dart
> +  }
why do we do that?

2024-12-09 13:11 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/bridge.dart
> +      if (!isValidStellarAddress(toAddress)) {
can we also block the bridge address?

2024-12-09 13:11 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/bridge.dart
> +        isWithdraw ? await TFChain.getMemo(fromController.text.trim()) : null;
```suggestion
        isWithdraw ? await TFChain.getMemo(toController.text.trim()) : null;
```

2024-12-12 09:12 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/bridge.dart
> +        toAddressError = 'Invaild Stellar address';
the address is valid but it's blocked. please split the conditions and use this error message for blocking the bridge address `Bridge address can't be the destination`

2024-12-12 09:23 UTC, AhmedHanafy725 approved these changes

2024-12-12 09:28 UTC, merged