add/edit stellar address in farm
threefoldtech/threefold_connect pull request #781
Opened 2024-11-27 11:12 UTC by AlaaElattar

- https://github.com/threefoldtech/threefold_connect/issues/730
- User can add or edit stellar address of farm
- also user can choose address from saved wallets
- address always being validated, won't be saved unless its correct.
### Tested Scenarios:
- Tried to save wrong address but failed as button is disabled.
- Tried to save right address and worked.
- Chose address from wallets and worked.

2024-11-27 11:20 UTC, AlaaElattar commented
Uploading 2024-11-27 13.13.03.mp4…

2024-12-01 14:10 UTC, zaelgohary requested changes
I could edit a stellar address with an invalid value. I think we should validate the address before adding/editing.

2024-12-01 14:15 UTC, zaelgohary reviewed
After clicking edit, there is no option to cancel the operation. To cancel editing, I would need to either click save or navigate back.

![image](https://github.com/user-attachments/assets/506e99a3-1e5e-4d77-bfbc-c6834f2cd7b0)

2024-12-01 14:22 UTC, zaelgohary commented
Clicking edit and navigating to the homepage without saving leaves the farming page stuck in the editing state.

2024-12-05 07:57 UTC, AlaaElattar commented
> After clicking edit, there is no option to cancel the operation. To cancel editing, I would need to click save.
> 
> ![image](https://private-user-images.githubusercontent.com/40770501/391338309-506e99a3-1e5e-4d77-bfbc-c6834f2cd7b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODU2ODYsIm5iZiI6MTczMzM4NTM4NiwicGF0aCI6Ii80MDc3MDUwMS8zOTEzMzgzMDktNTA2ZTk5YTMtMWU1ZS00ZDc3LWJmYmMtYzY4MzRmMmNkN2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA3NTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4YTE4NjNjZTViZDExZWQxNWY0M2QwNDgyZDc2ZjRmZGI5M2I0ODRkMTA5ODFiNmJmNTA5ZjZiODJjYmQzZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uivB-UbYSLX2xg4uRxptaTNRf9JRkeZoG7_cc8tnCh8)

- Done, added cancel button that appears while editing.
![2024-12-05 09 56 13](https://github.com/user-attachments/assets/9e87c426-0f26-43b4-9ffd-35833e68f9b6)

2024-12-05 09:15 UTC, AlaaElattar commented
> Clicking edit and navigating to the homepage without saving leaves the farming page stuck in the editing state.

tried to reproduce it but didn't happen

2024-12-11 11:30 UTC, AhmedHanafy725 requested changes

2024-12-11 11:30 UTC, AhmedHanafy725 commented on app/lib/widgets/farm_item.dart
> +      addressError =
can you also check if the address has TFT trustline?

2024-12-11 11:30 UTC, AhmedHanafy725 commented on app/lib/widgets/farm_item.dart
> +                                  wallets: widget.wallets,
can you exclude the wallets with `-1` balance?

2024-12-11 11:30 UTC, AhmedHanafy725 commented on app/lib/widgets/farm_item.dart
> +                                  currentWalletAddress:
after a successful update, the `widget.farm.walletAddress` is still the same as the old one, it should be updated to not show the current wallet in the contacts list

2024-12-11 13:20 UTC, zaelgohary approved these changes

2024-12-11 13:27 UTC, AhmedHanafy725 commented on app/lib/widgets/farm_item.dart
> +    setState(() {
please trim the address before start validating

2024-12-11 14:02 UTC, AhmedHanafy725 approved these changes

2024-12-11 14:02 UTC, AhmedHanafy725 commented on app/lib/widgets/farm_item.dart
> +  void _selectToAddress(String address) {
```suggestion
  void _selectAddress(String address) {

```

2024-12-11 14:02 UTC, AhmedHanafy725 commented on app/lib/widgets/farm_item.dart
> +      validateStellarAddress(address);
I don't think we should validate the address here

2024-12-11 14:06 UTC, merged