Fix max fee padding & add amount btns
threefoldtech/threefold_connect pull request #805
Opened 2024-12-12 09:15 UTC by zaelgohary

2024-12-16 15:33 UTC, AhmedHanafy725 requested changes
set the amount and wait for a couple of seconds, it will disappear

2024-12-16 15:33 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/send.dart
> +            (percentage / 100) -
in case of 0 balance, selecting any of the percentages will lead to a negative balance

2024-12-16 15:33 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/send.dart
> +                                      borderRadius: BorderRadius.zero)),
use a small radius instead of 0, it shouldn't be so sharp

2024-12-18 09:28 UTC, zaelgohary commented
> set the amount and wait for a couple of seconds, it will disappear

I couldn't reproduce this. I waited for more than 2 mins and nothing happened.

2024-12-22 09:41 UTC, AhmedHanafy725 approved these changes

2024-12-22 09:42 UTC, merged