Development_use_wallet_provider
threefoldtech/threefold_connect pull request #822
Opened 2024-12-24 15:16 UTC by zaelgohary

### Changes

List of changes this PR includes

### Related Issues

List of related issues

### Tested Scenarios

A list of scenarios tried to match the deliverables

2024-12-30 10:37 UTC, AhmedHanafy725 requested changes
- The provider should have a method for editing the wallet name. We shouldn't wait until the reload balance is called to update the name.
- Adding a new wallet doesn't use the provider.

2025-01-08 11:38 UTC, AhmedHanafy725 reviewed
the wallet name doesn't update in the appBar after editing 
https://github.com/user-attachments/assets/8839737a-9bd5-4679-86ae-e9524d7fd66b

2025-01-13 10:41 UTC, zaelgohary commented
> the wallet name doesn't update in the appBar after editing

I added a watcher to the wallet to reload the details on any change.

2025-01-14 11:01 UTC, AhmedHanafy725 approved these changes

2025-01-14 11:36 UTC, merged