support kyc for each wallet
threefoldtech/threefold_connect pull request #827
Opened 2024-12-25 12:24 UTC by AlaaElattar

### Changes

List of changes this PR includes

### Related Issues

List of related issues

### Tested Scenarios

A list of scenarios tried to match the deliverables

2025-01-13 07:27 UTC, zaelgohary commented
Workflow needs to be fixed.

2025-01-19 15:01 UTC, AhmedHanafy725 requested changes
the dialog size is too big

<img src="https://github.com/user-attachments/assets/9d82b1e7-d93d-4eb7-97ed-146c9568bc5f" width=250>

2025-01-19 15:01 UTC, AhmedHanafy725 commented on app/lib/helpers/kyc_helpers.dart
> -Future<void> saveCorrectVerificationStates(
why do you remove this method?

2025-01-19 15:01 UTC, AhmedHanafy725 commented on app/lib/widgets/wallets/wallet_card.dart
> +                    style: wallet.verificationStatus == 'VERIFIED'
can we make it a chip?

2025-01-19 15:01 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/wallet_info.dart
> +                    wallet.verificationStatus != 'VERIFIED'
please use the `VerificationStatus` enum
```suggestion
                    wallet.verificationStatus != VerificationState.VERIFIED.name

```

2025-01-19 15:01 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/wallet_info.dart
> +                    wallet.verificationStatus != 'VERIFIED'
please apply that everywhere

2025-01-19 15:01 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/wallet_info.dart
> +            Center(
please add some spacing after the KYC title

2025-01-19 15:01 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/wallet_info.dart
> +              'KYC Verification',
```suggestion
              'KYC',

```

2025-01-19 15:01 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/wallet_info.dart
> +            ),
What about adding a chip at the end of the KYC row?

2025-01-19 15:01 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/wallet_info.dart
> +                        : 'Show Verified Data',
```suggestion
                        ? 'Verify'
                        : 'Show Data',

```

2025-01-19 15:01 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/wallet_info.dart
> +                        : Theme.of(context).colorScheme.primaryContainer,
it's not dangerous to do the kyc verification
```suggestion
                    backgroundColor: Theme.of(context).colorScheme.primaryContainer,

```

2025-01-19 15:01 UTC, AhmedHanafy725 commented on app/lib/screens/wallets/wallet_info.dart
> +                                  .onPrimaryContainer,
```suggestion
                          color: Theme.of(context)
                                  .colorScheme
                                  .onPrimaryContainer,

```

2025-01-19 15:01 UTC, AhmedHanafy725 commented on app/lib/widgets/kyc_widget.dart
> +                        'No data available for the provided wallet address.',
add some padding 
<img src="https://github.com/user-attachments/assets/6f6df500-ade5-465d-90b3-e8dff99ac1a1" width=250>

2025-01-22 11:30 UTC, AlaaElattar commented on app/lib/helpers/kyc_helpers.dart
> -Future<void> saveCorrectVerificationStates(
I thought we don't need it anymore. what do think ?

2025-01-27 09:46 UTC, AhmedHanafy725 commented on app/lib/models/wallet.dart
> +  String verificationStatus;
can we use the `verificationStatus` type instead of string?

2025-01-27 09:46 UTC, AhmedHanafy725 commented on app/lib/helpers/kyc_helpers.dart
> -Future<void> saveCorrectVerificationStates(
I think it's useful to get the correct state if the storage is deleted and the account is recovered

2025-01-27 09:46 UTC, AhmedHanafy725 commented on app/lib/widgets/wallets/wallet_card.dart
> +                            ),
we might need the capitalize method in some places, so it would be nice if we have a method for it in helpers
```suggestion
                        wallet.verificationStatus[0].toUpperCase() + wallet.verificationStatus.substring(1).toLowerCase()
```

2025-01-27 11:48 UTC, AhmedHanafy725 approved these changes

2025-01-27 12:09 UTC, merged